title = "RacineDuCiel"
baseURL = "https://racineduciel.fr/"
theme = "ablog"
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

defaultContentLanguage = "fr-fr"

[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod", "date"]

[taxonomies]
  category = "categories"
  tag = "tags"
  type = "types"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.typographer]
  disable = false

[markup.goldmark.extensions.extras.mark]
  enable = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$'], ['\\[', '\\]']]
    inline = [['$', '$'], ['\\(', '\\)']]

[privacy.googleAnalytics]
  respectDoNotTrack = true

[privacy.youtube]
  privacyEnhanced = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[params]
  math = true
  browserconfig.TileColor = "#2d89ef"

[Languages.fr-fr]
  languageName = "French"
  languageCode = "fr-fr"
  contentDir = "content/"
  weight = 1

  [Languages.fr-fr.params]
    defaultColor = "auto"
    mainSections = ["posts", "rÃ©seau", "Sport"]
    toc = false
    goToTop = true
    dateFormat = "02/01/06"
    rssFeedDescription = "summary"
    additionalScripts = []

    [Languages.fr-fr.params.author]
      avatar = "avatar.jpg"
      description = "ğ•ğ•™ğ•’ğ•¥ ğ••ğ• ğ•–ğ•¤ ğ•šğ•¥ ğ•ğ•–ğ•’ğ•Ÿ ğ•¥ğ•  ğ•“ğ•– ğ•™ğ•¦ğ•ğ•’ğ•Ÿ"
      name = "RacineDuCiel"

    [Languages.fr-fr.params.webmanifest]
      start_url = "/"
      theme_color = "#434648"
      background_color = "#fff"
      display = "standalone"

    [Languages.fr-fr.params.seo]
      images = ["og-image.jpg"]

   [[Languages.fr-fr.menu.main]]
    pageRef = "/"
    name = "Accueil"
    url = "/"
    weight = 10
  [[Languages.fr-fr.menu.main]]
    pageRef = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 20
  [[Languages.fr-fr.menu.main]]
    pageRef = "partages"
    name = "Partages"
    url = "/partages/"
    weight = 30
  [[Languages.fr-fr.menu.main]]
    name = "CatÃ©gories"
    url = "/categories/"
    weight = 32
  [[Languages.fr-fr.menu.main]]
    pageRef = "about"
    name = "Ã€ propos"
    url = "/about/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[[Languages.fr-fr.menu.main]]
  name = "Recherche"
  url = "/search/"
  weight = 35

